#!/bin/bash

. /opt/helpers

service npcd start

# Allow any signal which would kill a process to stop server
trap "service apache2 stop" HUP INT QUIT ABRT ALRM TERM TSTP

while pgrep -u nagios npcd > /dev/null; do sleep 5; done
